### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by Robertfarb** [Robertfarb/campout#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by eshoule** [comment]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in


## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)

Good job, Rob! Fix the unchecked items and the below comments, and I will close the issue.
* You need to add a Sign Up link in the header on the splash page
* You should have a link on both your sign in and sign up modals that links to the other modal.

**Comment by Robertfarb** [comment]
- [X] Added signup link top the nav bar
- [X] Added login link to the signup modal
- [X] /signup /login don't take user anywhere since I'm using modals
- [X] Added signup link top the nav bar
- [X] Added 404 not found page when visiting a random link
