### ISSUE TITLE
PA Review: Listings

### ISSUE THREAD

**Issue by Robertfarb** [Robertfarb/campout#3]
- [x] Users can view Listings index that displays all listings
- [x] Listings show page will include an image gallery, feature, activities and a description of the site
- [x] Adequate styling
- [x] Smooth, bug free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by Robertfarb** [comment]
Listings index will include a list of filters on the left and a map on the right once I get to my Search MVP

**Comment by eshoule** [comment]
* Are you going to allow the user to scroll through the photos on the show page? Right now I can only see 2.5 of the images on the show page, ha.
