### ISSUE TITLE
PA Review: Bookings

### ISSUE THREAD

**Issue by Robertfarb** [Robertfarb/campout#4]
- [x] Logged in Users can book a listing for certain dates
- [x] Logged in Users can cancel their booking
- [x]  Logged in Users can view their past / upcoming bookings
- [x]  Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by eshoule** [comment]
* When I click on book without selecting any options, it just brings me to a blank page. Maybe throw an error message?
* Should we be allowing overlapping bookings?
* How do I navigate to my bookings from the home page? Right now it seems the only way to do this is to create a booking.

**Comment by Robertfarb** [comment]
- [x] user icon and username is a link to the bookings page
- [x] throw an error when booking form is submitted with no values
- I was planning on handling overlapping bookings as a bonus MVP if I get there, since Search is a core functionality and I wanted to get that rolled out and styled before I add extras to my core functionalities

**Comment by eshoule** [comment]
Sounds good, Rob!

**Comment by eshoule** [comment]
Awesome!
